server.port=8090
# Configuración para Postgres en Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/edusmart_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
# Esto ayuda a que Hibernate use el dialecto correcto de Postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect